# list of translations
# last update: 2017-06-12

oydLocalization <- list(
        'okLbl' = list('de' = 'OK',
                       'en' = 'OK'),
        'cancelLbl' = list('de' = 'Abbrechen',
                           'en' = 'Cancel'),
        'closeLbl' = list('de' = 'Schließen',
                          'en' = 'Close'),
        'passwordLbl' = list('de' = 'Passwort',
                             'en' = 'Password'),
        'keyLbl' = list('de' = 'Verwendeter Schlüssel',
                        'en' = 'Master Key'),
        'decryptLbl' = list('de' = 'Entschlüsseln',
                            'en' = 'Decrypt'),
        'encryptLbl' = list('de' = 'Verschlüsseln',
                            'en' = 'Encrypt'),
        'my_apps' = list('de' = 'Meine Apps', 'en' = 'My Apps'),
        'menu_help' = list('de' = 'Hilfe', 'en' = 'Help'),
        'section_analysis' = list('de' = 'Auswertungen', 'en' = 'Data Analysis'),
        'section_source' = list('de' = 'Datenquellen', 'en' = 'Data Sources'),
        'section_report' = list('de' = 'Bericht', 'en' = 'Report'),
        'OwnYourData' = list('de' = 'Deutsch', 'en' = 'English'),
        'versionMenuItem' = list('de' = 'Version', 'en' = 'Version'),
        'documentationMenuItem' = list('de' = 'Dokumentation', 'en' = 'Documentation'),
        'configMenuItem' = list('de' = 'Konfiguration', 'en' = 'Configuration'),
        'aboutOYD' = list('de' = 'über OwnYourData.eu', 'en' = 'about OwnYourData.eu'),
        'mobileApps' = list('de' = 'Mobiler Datentresor', 'en' = 'Mobile Data Vault'),
        'sendFeedback' = list('de' = 'Feedback senden', 'en' = 'Send Feedback'),
        'ctrlTrnsl_langLabel' = list('de' = 'Sprache:', 'en' = 'Language:'),
        'ctrlTrnsl_backToAppBtn' = list('de' = 'Zurück', 'en' = 'Back'),
        'readDataProgressMsg' = list('de' = 'lese Daten', 'en' = 'read data'),

        # Start Config Dialog
        'ctrlTrnsl_configDialogTitle' = list('de' = 'Konfiguration', 'en' = 'Configuration'),
        'ctrlTrnsl_configDialogStep1' = list('de' = 'Willkommen (Schritt 1 von 4)', 'en' = 'Welcome (Step 1 of 4)'),
        'ctrlTrnsl_configDialogStep1Text' = list('de' = 'Dieser Assistent hilft dir dabei die App einzurichten. Klicke auf "Weiter", um zum nächsten Schritt zu gelangen!',
                                       'en' = 'This dialog assits you to configure your App. Click "Next" to start!'),
        'ctrlTrnsl_configDialogStep1BtnNext' = list('de' = 'Weiter', 'en' = 'Next'),
        'ctrlTrnsl_configDialogStep2' = list('de' = 'Datentresor (Schritt 2 von 4)', 'en' = 'Data Vault (Step 2 of 4)'),
        'ctrlTrnsl_configDialogStep2Text' = list('de' = 'Trage hier die Verbindungdaten zu deinem Datentresor ein. Du findest diese Informationen im Datentresor bei jeder App unter "Details".',
                                       'en' = 'Enter here the connection details to your data vault. You find this information in your data vault at the respective app by clicking on "Details".'),
        'ctrlTrnsl_configDialogStep2UrlInput' = list('de' = 'Adresse (URL):', 'en' = 'Address (URL):'),
        'ctrlTrnsl_configDialogStep2IdInput' = list('de' = 'Kennzeichen (ID):', 'en' = 'Identifier (ID):'),
        'ctrlTrnsl_configDialogStep2SecretInput' = list('de' = 'Geheimnis:', 'en' = 'Secret:'),
        'ctrlTrnsl_configDialogStep2IdInput' = list('de' = 'Kennung:', 'en' = 'Identifier:'),
        'ctrlTrnsl_configDialogStep2SecretInput' = list('de' = 'Geheimnis:', 'en' = 'Secret:'),
        'configDialogStep2currentTokenLbl' = list('de' = 'aktueller Token:', 'en' = 'current token:'),
        'noPiaResponseError' = list('de' = 'Fehler: keine Antwort vom Datentresor', 'en' = 'Error: no response from data vault'),
        'malformedPiaUrl' = list('de' = 'Fehler: ungültige Adresse des Datentresors', 'en' = 'Error: invalid data vault URL'),
        'errorLbl' = list('de' = 'Fehler:', 'en' = 'Error:'),
        'ctrlTrnsl_configDialogStep2disconnectPiaBtn' = list('de' = 'Verbindung zum Datentresor trennen', 'en' = 'Disconnect from Data Vault'),
        'ctrlTrnsl_configDialogStep2BtnNext' = list('de' = 'Speichern & Weiter', 'en' = 'Save & Next'),
        'ctrlTrnsl_configDialogStep2BtnBack' = list('de' = 'Zurück', 'en' = 'Back'),
        'ctrlTrnsl_configDialogStep2BtnSkip' = list('de' = 'Überspringen', 'en' = 'Skip'),

        'ctrlTrnsl_configDialogStep3' = list('de' = 'Verschlüsselung (Schritt 3 von 4)',
                                             'en' = 'Encryption (Step 3 of 4)'),
        'ctrlTrnsl_configDialogStep3Text' = list('de' = 'Falls deine Daten im Datentresor verschlüsselt abgelegt werden sollen (empfohlen!) kannst du hier die dafür notwendigen Schlüssel erfassen.',
                                                 'en' = 'Enter here the keys for encryption/decryption if you want to use encryption with your data vault. (recommended!)'),
        'ctrlTrnsl_configDialogStep3KeyList' = list('de' = 'vorhandene Schlüssel',
                                                    'en' = 'available keys'),
        'ctrlTrnsl_configDialogStep3DeleteKey' = list('de' = 'Entfernen',
                                                      'en' = 'Remove'),
        'ctrlTrnsl_configDialogStep3ImportBtn' = list('de' = 'Import...',
                                                      'en' = 'Import...'),
        'ctrlTrnsl_configDialogStep3ExportBtn' = list('de' = 'Export...',
                                                      'en' = 'Export...'),
        'ctrlTrnsl_configDialogStep3KeyTitle' = list('de' = 'Name',
                                                     'en' = 'Title'),
        'ctrlTrnsl_configDialogStep3KeyRepo' = list('de' = 'Liste',
                                                    'en' = 'Repo'),
        'ctrlTrnsl_configDialogStep3KeyKeystr' = list('de' = 'Schlüssel',
                                                      'en' = 'Key'),
        'ctrlTrnsl_configDialogStep3KeyType' = list('de' = 'Typ',
                                                    'en' = 'Type'),
        'ctrlTrnsl_configDialogStep3KeyAdd' = list('de' = 'Hinzufügen',
                                                   'en' = 'Add'),
        'ctrlTrnsl_configDialogStep3KeyUpdate' = list('de' = 'Aktualisieren',
                                                      'en' = 'Update'),
        'ctrlTrnsl_configDialogStep3KeyResetForm' = list('de' = 'zurücksetzen',
                                                         'en' = 'reset'),
        'keyLbl' = list('de' = 'Schlüssel',
                        'en' = 'Key'),
        'writeOnlyLbl' = list('de' = 'Schlüssel darf nur schreiben',
                              'en' = 'key must only write'),
        'keyGenerateSpan' = list('de' = 'Gib hier den Text ein, der zur Verschlüsselung verwendet werden soll.',
                                 'en' = 'Enter here the text that will be used for encryption.'),
        'missingInputError' = list('de' = 'Fehlende Eingabe im Feld "Schlüssel"!',
                                   'en' = 'Missing input in field "Key"!'),
        'keyExportTitle' = list('de' = 'Schlüssel exportieren',
                                'en' = 'Export Keys'),
        'exportKeyDescriptionSpan' = list('de' = 'Schlüssel exportieren',
                                          'en' = 'Key export'),
        'writeOnlyOption' = list('de' = 'nur Schreiben',
                                 'en' = 'Write only'),
        'readWriteOption' = list('de' = 'Schreiben & Lesen',
                                  'en' = 'Write & Read'),
        'keyExportTypeLbl' = list('de' = 'Speicherort',
                                  'en' = 'Location'),
        'fileOption' = list('de' = 'Textdatei (JSON)',
                                'en' = 'Text File (JSON)'),
        'localStorageOption' = list('de' = 'Web Browser (Local Storage)',
                                    'en' = 'Web Browser (Local Storage)'),
        'piaOption' = list('de' = 'Datentresor',
                           'en' = 'Data Vault'),
        'encryptKeyExportLbl' = list('de' = 'Ausgabe verschlüsseln, Passwort:',
                                     'en' = 'encrypt output, Password:'),
        'exportKeysLbl' = list('de' = 'Speichern',
                               'en' = 'Save'),
        'keyImportTitle' = list('de' = 'Schlüssel importieren',
                                'en' = 'Key import'),
        'keyImportTypeLbl' = list('de' = 'Speicherort',
                                  'en' = 'Location'),
        'decryptKeyImportLbl' = list('de' = 'Daten entschlüsseln, Passwort:',
                                     'en' = 'decrypt data, Password:'),
        'failedImportError' = list('de' = 'Schlüssel konten nicht importiert werden',
                                   'en' = 'unable to import keys'),
        'importKeysLbl' = list('de' = 'Importieren',
                               'en' = 'Import'),
        'keyImportFileLbl' = list('de' = 'Dateiauswahl:',
                                  'en' = 'Select file:'),
        'exportclearKeyStorageBtn' = list('de' = 'Schlüssel im Webbrowser entfernen',
                                          'en' = 'remove keys from web browser'),
        'invalidKeyDataLocalStorageTxt' = list('de' = 'ungültige Schlüsseldaten sind im Webbrowser gespeichert',
                                               'en' = 'invalid key data is stored in your web browser'),
        'validKeyDataLocalStorageTxt' = list('de' = 'Schlüsseldaten sind im Webbrowser gespeichert',
                                             'en' = 'encrypted key data is stored in your web browser'),
        'numberKeyDataLocalStorageTxt' = list('de' = 'Schlüssel sind im Webbrowser gepspeichert',
                                              'en' = 'key(s) are stored in your web browser'),
        'noKeyDataLocalStorageTxt' = list('de' = 'keine Schlüssel sind im Webbrowser gespeichert',
                                          'en' = 'no keys are stored in your web browser'),
        'errorExistingKeyDataLocalStorage' = list('de' = 'Es sind bereits Schlüsseldaten im Webbrowser gespeichert und diese können nicht überschrieben werden. Entferne diese Daten bevor du die aktuellen Schlüssel speicherst!',
                                                  'en' = 'There are already keys stored in your web browser. Remove those first before you save the current keys!'),
        'decryptDialogTitle' = list('de' = 'Datenzugriff',
                                    'en' = 'Data Access'),
        'encryptDialogText' = list('de' = 'Du öffnest diese App das erste Mal und kannst hier festlegen, ob und wie deine Daten verschlüsselt werden sollen.',
                                   'en' = 'You started this app for the first time and you can decide now, if and how to encrypt your data.'),
        'decryptDialogText' = list('de' = 'Deine Daten sind verschlüsselt.',
                                   'en' = 'You data is encrypted.'),
        'currentlyNoEncryptionText' = list('de' = 'derzeit keine Schlüssel',
                                           'en' = 'currently no keys'),
        'encryptOptionsLbl' = list('de' = 'Wie sollen deine Daten verschlüsselt werden?',
                                   'en' = 'How to encrypt your data?'),
        'encryptSimpleOption' = list('de' = 'ein Schlüssel für deinen Datentresor',
                                     'en' = 'a single key for your data vault'),
        'encryptAppOption' = list('de' = 'ein eigener Schlüssel für jede App (empfohlen)',
                                  'en' = 'a different key for each app (recommended)'),
        'encryptCustomOption' = list('de' = 'benutzerdefinierte Verschlüsselung festlegen',
                                     'en' = 'use custom encryption'),
        'missingSimpleEncryptPassword' = list('de' = 'fehlender Schlüssel',
                                              'en' = 'missing key'),
        'missingAppEncryptPassword' = list('de' = 'fehlendes Passwort',
                                              'en' = 'missing password'),
        'exportSingleKeyTxt' = list('de' = 'nur ausgewählten Schlüssel exportieren',
                                    'en' = 'export only selected key'),
        'simpleEncryptInfo' = list('de' = 'Bei dieser Option werden alle Daten im Datentresor mit dem gleichen Schlüssel codiert. Gib beim Start der App diesen Schlüssel immer an.',
                                   'en' = 'Use this option to encrypt all your data with a single key. Enter that key during startup of an app.'),
        'appEncryptInfo' = list('de' = 'Es wird automatisch ein geheimer Schlüssel für alle Daten dieser App erstellt und im Webbrowser mit dem gewählten Passwort gespeichert. Ebenfalls soll der so erstellte Schlüssel an einem sicheren Ort gespeichert werden - verwende dazu die Download-Schaltfläche neben dem Passwortfeld.',
                                'en' = 'The systen generates a secret key  for the data of this app and stores this key in your browser secured with the chosen password. Download this automatically generated key and store it at a safe location.'),
        'customEncryptInfo' = list('de' = 'Öffne im Menü rechts oben "Konfiguration" und erstelle dort die notwendigen Schlüssel.',
                                   'en' = 'Open the menu in the upper right corner and create the necessary keys.'),
        'checkInconsistencyWriteEncryptedTxt' = list('de' = 'Du möchtest verschlüsselte Informationen in eine bisher unverschlüsselte Liste schreiben und damit werden Inkonsistenzen erzeugt. Möchtest du wirklich fortfahren?',
                                                     'en' = 'You are going to write encrypted data into an unencrypted repo and this will lead to inconsistencies. Do you really want to proceed?'),
        'checkInconsistencyWriteUnencryptedTxt' = list('de' = 'Du möchtest unverschlüsselte Informationen in eine bisher verschlüsselte Liste schreiben und damit werden Inkonsistenzen erzeugt. Möchtest du wirklich fortfahren?',
                                                     'en' = 'You are going to write unencrypted data into an encrypted repo and this will lead to inconsistencies. Do you really want to proceed?'),
        'ctrlTrnsl_configDialogStep3BtnNext' = list('de' = 'Weiter', 'en' = 'Next'),
        'ctrlTrnsl_configDialogStep3BtnBack' = list('de' = 'Zurück', 'en' = 'Back'),
        'ctrlTrnsl_configDialogStep4' = list('de' = 'Fertig (Schritt 4 von 4)', 'en' = 'Complete (Step 4 of 4)'),
        'ctrlTrnsl_configDialogStep4Text' = list('de' = 'Gratulation! Du hast alle notwendigen Einstellungen vorgenommen und kannst nun die App verwenden. Solltest du später eine Änderung vornehmen wollen, findest du diesen Dialog im Menü rechts oben unter dem Eintrag "Konfiguration".',
                                                 'en' = 'Congratulation! You have successfully configured your app. If your want to change any settings later, you can re-open this dialog in the upper right corner menu titled "Configuration".'),
        'ctrlTrnsl_configDialogStep4BtnBack' = list('de' = 'Zurück', 'en' = 'Back'),
        'ctrlTrnsl_configDialogStep4BtnFinish' = list('de' = 'Fertig', 'en' = 'Finish'),

        'configDialogCloseBtn' = list('de' = 'Schließen', 'en' = 'Close'),

        # Help Text
        'source_help' = list('de' = 'Datenquellen Hile', 'en' = 'Datasource Help'),

        # Notifications
        'msgRecordsRead' = list('de' = 'Datensätze gelesen', 'en' = 'records read'),
        'piaReadError' = list('de' = 'Fehler beim Lesen', 'en' = 'read error'),
        'piaReadWarning' = list('de' = 'Warnung beim Lesen', 'en' = 'read warning'),
        'piaPermissionReadError' = list('de' = 'fehlende Zugriffsberechtigung',
                                        'en' = 'access denied'),
        'piaUnknownRepoReadError' = list('de' = 'Liste nicht vorhanden',
                                         'en' = 'unknown repo'),
        'msgNoRecords' = list('de' = 'derzeit sind noch keine Datensätze für diese App vorhanden',
                              'en' = 'there are no records for this app available yet'),
        'msgUnencryptedDataWithKey' = list('de' = 'unverschlüsselte Daten trotz vorhandem Schlüssel gefunden',
                                           'en' = 'found unencrypted data despite existing key'),
        'msg1RecordWrite' = list('de' = 'Datensatz gespeichert', 'en' = 'record saved'),
        'msgRecordsWrite' = list('de' = 'Datensätze gespeichert', 'en' = 'records saved'),
        'msgRecordUpdate' = list('de' = 'Datensatz geändert', 'en' = 'record updated'),
        'piaWriteError' = list('de' = 'Fehler beim Schreiben', 'en' = 'write error'),
        'piaUpdateError' = list('de' = 'Fehler beim Ändern', 'en' = 'update error'),
        'piaPermissionDeleteError' = list('de' = 'Fehler beim Löschen (fehlende Zugriffsberechtigung)',
                                          'en' = 'delete error (access denied)'),
        'piaPermissionWriteError' = list('de' = 'fehlende Zugriffsberechtigung',
                                         'en' = 'access denied'),
        'msgCantParseJSON' = list('de' = 'Datenformat wurde nicht erkannt',
                                  'en' = 'unknown data format'),
        'msgDecryptError' = list('de' = 'ungültiger Schlüssel',
                                 'en' = 'invalid key'),
        'msgMissingKey' = list('de' = 'fehlender Schlüssel',
                               'en' = 'missing key'),
        'msgRecordDelete' = list('de' = 'Datensatz gelöscht',
                                 'en' = 'record deleted'),
        'msgDeleteRecordMissing' = list('de' = 'Fehler beim Löschen des Datensatzes (Datensatz nicht gefunden)',
                                        'en' = 'Error on deleting record (record not found)'),
        'msgDeleteRecordError' = list('de' = 'Fehler beim Löschen des Datensatzes',
                                      'en' = 'Error on deleteing record'),
        'msgNameInUse' = list('de' = 'Name bereits vergeben',
                              'en' = 'Title is not unique'),
        'msgNoKeySelected' = list('de' = 'kein Schlüssel ausgewählt',
                                  'en' = 'no key selected'),
        'msgInvalidKey' = list('de' = 'ungültiger Schlüssel (verwende genau 64 Zeichen mit den Ziffern 0-9 und den Buchstaben a-f)',
                               'en' = 'invalid key (use exactly 64 characters with number 0-9 and letters a-f)'),
        'msgKeyImport' = list('de' = 'Schlüssel importiert',
                              'en' = 'key(s) imported'),
        'msgKeyExportBrowser' = list('de' = 'Schlüssel im Browser gespeichert',
                                     'en' = 'key(s) stored in Browser'),
        'msgKeyExportBrowserUnencrypted' = list('de' = 'Schlüssel im Browser unverschlüsselt gespeichert',
                                                'en' = 'key(s) stored in Browser unencrypted'),
        'msgInvalidEncryptedKeyImport' = list('de' = 'ungültiges Format der verschlüsselten Schlüssel-Daten',
                                              'en' = 'invalid format of encrypted key data'),
        'msgDuplicateKeys' = list('de' = 'Mindesten einer der zu importierenden Schlüssel wird bereits verwendet und der Import wurde daher abgebrochen.',
                                  'en' = 'At least one key is already in use and therefore the import was canceled.'),
        'msgInvaldImport' = list('de' = 'Der Datenimport enthält keine oder ungültige Schlüsselinformationen.',
                                 'en' = 'The selected data has no or invalid key information.'),
        'msgNewConnectionData' = list('de' = 'Es wurden neue Verbindungsdaten zum Datentresor übergeben und gespeichert.',
                                      'en' = 'New connection data was provided and stored.'),
        'msgInvalidDecryptKey' = list('de' = 'ungültiger Schlüssel',
                                      'en' = 'invalid key'),
        'msgUnencryptedData' = list('de' = 'Die Daten in deinem Datentresor sind nicht veschlüsselt.',
                                    'en' = 'Data in your data vault is not encrypted.'),
        'msgUnencryptedKeyInfo' = list('de' = 'Die Schlüsseldaten sind unverschlüsselt in deinem Browser gespeichert!',
                                       'en' = 'The key data is stored unencrypted in your web browser!'),
        'msgCorruptKeyInfo' = list('de' = 'Die Schlüsseldaten in deinem Browser sind ungültig.',
                                   'en' = 'The key data stored in your browser is invald.'),
        'msgExportKeyListNoKeys' = list('de' = 'Es sind keine Schlüssel zum Exportieren vorhanden.',
                                        'en' = 'There are no keys to export.'),

        # Alert Messages
        'piaConnectionMsgTitle' = list('de' = 'Keine Verbindung zum Datentresor', 'en' = 'No Data Vault Connection'),
        'missingIncompletePiaData' = list(
                'de' = paste0('Es sind keine oder nur unvollständige Verbindungsdaten vorhanden. Wähle im Menü ',
                              shiny::icon('gear'),
                              ' rechts oben "Konfiguration" und trage dort die Verbindungsdaten zu deinem Datentresor ein!'),
                'en' = paste0('There is no or incomplete information about your data vault. Select the ',
                              shiny::icon('gear'),
                              ' menu in the upper right corner and open the "Configuration" dialog to enter connection details!')),
        'invalidPiaData' = list(
                'de' = paste0('Die angegebenen Verbindungsdaten zum Datentresor sind nicht korrekt oder der Datentresor kann derzeit nicht erreicht werden. Öffne deinen Datentresor und überprüfe hier im Menü ',
                              shiny::icon('gear'),
                              ' rechts oben "Konfiguration" die gespeicherten Informationen!'),
                'en' = paste0('The provided connectiondata for your data vault is either incorrect or your data vault is not reachable. Open your data vault and check the connection data in the',
                              shiny::icon('gear'),
                              ' menu in the upper right corner and open the "Configuration" dialog to update connection details!')),
        'piaEncryptedMsgTitle' = list('de' = 'Verschlüsselter Datentresor',
                                      'en' = 'Encrypted Data Vault'),
        'piaEncryptedMsg' = list('de' = paste0('Die Daten in deinem Datentresor sind verschlüsselt und müssen vor der Verwendung entschlüsselt werden. Öffne im Menü ',
                                               shiny::icon('gear'),
                                               ' rechts oben "Konfiguration" und importiere die notwendigen Schlüssel!'),
                                 'en' = paste0('The data in your data vault is encrypted and needs to be decrypted before you can use ist. Open the ',
                                               shiny::icon('gear'),
                                               ' menu in the upper right corner and open the "Configuration" dialog to import the necessary keys!')),
        'piaEncryptedDataCorruptKeyInfoTitle' = list('de' = 'Ungültige Schlüsseldaten',
                                                     'en' = 'Invalid Key Data'),
        'piaEncryptedDataCorruptKeyInfoMsg' = list('de' = paste0('Die Daten in deinem Datentresor sind verschlüsselt und müssen vor der Verwendung entschlüsselt werden. Öffne im Menü ',
                                                                 shiny::icon('gear'),
                                                                 ' rechts oben "Konfiguration" und korrigiere die im Webbrowser gespeicherten Schlüssel!'),
                                                   'en' = paste0('The data in your data vault is encrypted and needs to be decrypted before you can use ist. Open the ',
                                                                 shiny::icon('gear'),
                                                                 ' menu in the upper right corner and open the "Configuration" dialog to fix the keys stored in your web browser!'))
)
